"""initial_schema

Revision ID: d791d1d8c0f0
Revises: 
Create Date: 2026-05-23 09:32:59.346632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd791d1d8c0f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_call_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_call_log_timestamp'), 'api_call_log', ['timestamp'], unique=False)
    op.create_table('equity_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cash_balance', sa.Float(), nullable=False),
    sa.Column('position_value', sa.Float(), nullable=False),
    sa.Column('total_equity', sa.Float(), nullable=False),
    sa.Column('open_position_count', sa.Integer(), nullable=False),
    sa.Column('daily_pnl', sa.Float(), nullable=False),
    sa.Column('weekly_pnl', sa.Float(), nullable=False),
    sa.Column('all_time_pnl', sa.Float(), nullable=False),
    sa.Column('shadow_equity', sa.Float(), nullable=False),
    sa.Column('current_tier', sa.Integer(), nullable=False),
    sa.Column('rolling_7d_avg_bankroll', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equity_snapshots_timestamp'), 'equity_snapshots', ['timestamp'], unique=False)
    op.create_table('notification_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('message_hash', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_log_message_hash'), 'notification_log', ['message_hash'], unique=False)
    op.create_index(op.f('ix_notification_log_timestamp'), 'notification_log', ['timestamp'], unique=False)
    op.create_table('tier_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('from_tier', sa.Integer(), nullable=False),
    sa.Column('to_tier', sa.Integer(), nullable=False),
    sa.Column('trigger_reason', sa.String(length=30), nullable=False),
    sa.Column('rolling_avg_at_change', sa.Float(), nullable=False),
    sa.Column('trade_size_new', sa.Float(), nullable=False),
    sa.Column('max_positions_new', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tier_history_timestamp'), 'tier_history', ['timestamp'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('disqualified_reasons', sa.JSON(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('win_rate_vs_category_floor_score', sa.Float(), nullable=False),
    sa.Column('closed_trades_count', sa.Integer(), nullable=False),
    sa.Column('months_active', sa.Float(), nullable=False),
    sa.Column('primary_category', sa.String(length=50), nullable=False),
    sa.Column('category_diversity_count', sa.Integer(), nullable=False),
    sa.Column('category_win_rate_floor', sa.Float(), nullable=False),
    sa.Column('avg_holding_minutes', sa.Float(), nullable=False),
    sa.Column('max_drawdown_pct', sa.Float(), nullable=False),
    sa.Column('single_market_pnl_pct', sa.Float(), nullable=False),
    sa.Column('volume_5min_crypto_pct', sa.Float(), nullable=False),
    sa.Column('volume_15min_crypto_pct', sa.Float(), nullable=False),
    sa.Column('positive_roi_pct', sa.Float(), nullable=False),
    sa.Column('profit_factor', sa.Float(), nullable=False),
    sa.Column('hold_to_resolution_pct', sa.Float(), nullable=False),
    sa.Column('consistency_score', sa.Float(), nullable=False),
    sa.Column('conviction_signal', sa.Float(), nullable=False),
    sa.Column('crowding_score', sa.Float(), nullable=False),
    sa.Column('crowding_score_baseline', sa.Float(), nullable=False),
    sa.Column('domain_score', sa.Float(), nullable=False),
    sa.Column('entropy_score', sa.Float(), nullable=False),
    sa.Column('insider_proximity_score', sa.Float(), nullable=False),
    sa.Column('counter_trade_signal', sa.Float(), nullable=False),
    sa.Column('is_counter_trade_candidate', sa.Boolean(), nullable=False),
    sa.Column('cluster_id', sa.String(length=100), nullable=True),
    sa.Column('cluster_size', sa.Integer(), nullable=False),
    sa.Column('last_trade_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shadow_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shadow_copies_count', sa.Integer(), nullable=False),
    sa.Column('shadow_pnl_usd', sa.Float(), nullable=False),
    sa.Column('shadow_capture_ratio', sa.Float(), nullable=True),
    sa.Column('shadow_failed_cycles', sa.Integer(), nullable=False),
    sa.Column('consecutive_losses_for_bot', sa.Integer(), nullable=False),
    sa.Column('recent_capture_ratio', sa.Float(), nullable=True),
    sa.Column('suspension_count_60d', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_address'), 'wallets', ['address'], unique=True)
    op.create_index(op.f('ix_wallets_status'), 'wallets', ['status'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('wallet_id', sa.BigInteger(), nullable=False),
    sa.Column('wallet_status_at_signal', sa.String(length=20), nullable=False),
    sa.Column('market_id', sa.String(length=100), nullable=False),
    sa.Column('token_id', sa.String(length=100), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('value_usd', sa.Float(), nullable=False),
    sa.Column('lead_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_shadow', sa.Boolean(), nullable=False),
    sa.Column('dedup_key', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_dedup_key'), 'signals', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_signals_is_shadow'), 'signals', ['is_shadow'], unique=False)
    op.create_index(op.f('ix_signals_lead_timestamp'), 'signals', ['lead_timestamp'], unique=False)
    op.create_index('ix_signals_lead_ts_wallet', 'signals', ['wallet_id', 'lead_timestamp'], unique=False)
    op.create_index(op.f('ix_signals_market_id'), 'signals', ['market_id'], unique=False)
    op.create_index(op.f('ix_signals_status'), 'signals', ['status'], unique=False)
    op.create_index(op.f('ix_signals_wallet_id'), 'signals', ['wallet_id'], unique=False)
    op.create_table('wallet_performance',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('wallet_id', sa.BigInteger(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('copies_executed', sa.Integer(), nullable=False),
    sa.Column('copies_won', sa.Integer(), nullable=False),
    sa.Column('copies_lost', sa.Integer(), nullable=False),
    sa.Column('copies_open', sa.Integer(), nullable=False),
    sa.Column('net_pnl_for_bot', sa.Float(), nullable=False),
    sa.Column('signal_to_exec_ratio', sa.Float(), nullable=False),
    sa.Column('shadow_period', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wallet_perf_wallet_period', 'wallet_performance', ['wallet_id', 'period'], unique=False)
    op.create_index(op.f('ix_wallet_performance_computed_at'), 'wallet_performance', ['computed_at'], unique=False)
    op.create_index(op.f('ix_wallet_performance_wallet_id'), 'wallet_performance', ['wallet_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.BigInteger(), nullable=True),
    sa.Column('wallet_id', sa.BigInteger(), nullable=False),
    sa.Column('market_id', sa.String(length=100), nullable=False),
    sa.Column('token_id', sa.String(length=100), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('size_shares', sa.Float(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_shadow', sa.Boolean(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_reason', sa.String(length=30), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('realized_pnl_usd', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl_usd', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_is_shadow'), 'positions', ['is_shadow'], unique=False)
    op.create_index(op.f('ix_positions_market_id'), 'positions', ['market_id'], unique=False)
    op.create_index(op.f('ix_positions_opened_at'), 'positions', ['opened_at'], unique=False)
    op.create_index(op.f('ix_positions_signal_id'), 'positions', ['signal_id'], unique=False)
    op.create_index(op.f('ix_positions_status'), 'positions', ['status'], unique=False)
    op.create_index(op.f('ix_positions_wallet_id'), 'positions', ['wallet_id'], unique=False)
    op.create_table('position_state_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('position_id', sa.BigInteger(), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=False),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_state_log_position_id'), 'position_state_log', ['position_id'], unique=False)
    op.create_index(op.f('ix_position_state_log_timestamp'), 'position_state_log', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_position_state_log_timestamp'), table_name='position_state_log')
    op.drop_index(op.f('ix_position_state_log_position_id'), table_name='position_state_log')
    op.drop_table('position_state_log')
    op.drop_index(op.f('ix_positions_wallet_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_status'), table_name='positions')
    op.drop_index(op.f('ix_positions_signal_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_opened_at'), table_name='positions')
    op.drop_index(op.f('ix_positions_market_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_is_shadow'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_wallet_performance_wallet_id'), table_name='wallet_performance')
    op.drop_index(op.f('ix_wallet_performance_computed_at'), table_name='wallet_performance')
    op.drop_index('ix_wallet_perf_wallet_period', table_name='wallet_performance')
    op.drop_table('wallet_performance')
    op.drop_index(op.f('ix_signals_wallet_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_status'), table_name='signals')
    op.drop_index(op.f('ix_signals_market_id'), table_name='signals')
    op.drop_index('ix_signals_lead_ts_wallet', table_name='signals')
    op.drop_index(op.f('ix_signals_lead_timestamp'), table_name='signals')
    op.drop_index(op.f('ix_signals_is_shadow'), table_name='signals')
    op.drop_index(op.f('ix_signals_dedup_key'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_wallets_status'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_address'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_tier_history_timestamp'), table_name='tier_history')
    op.drop_table('tier_history')
    op.drop_index(op.f('ix_notification_log_timestamp'), table_name='notification_log')
    op.drop_index(op.f('ix_notification_log_message_hash'), table_name='notification_log')
    op.drop_table('notification_log')
    op.drop_index(op.f('ix_equity_snapshots_timestamp'), table_name='equity_snapshots')
    op.drop_table('equity_snapshots')
    op.drop_index(op.f('ix_api_call_log_timestamp'), table_name='api_call_log')
    op.drop_table('api_call_log')
    # ### end Alembic commands ###
